### ISSUE TITLE
Record any errors while getting the setup

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/axi4_avip#68]
What happens when you source multiple times.

**Comment by mahadevaswamy05** [comment]
**1.When you cloned two times that SVUnit Repository-like name is SVUnit_1 and SVUnit_2.
 and both have their respective source file like a Setup.csh using this we're source the environmental variable and path for execution.** 
 
follow the below picture for more clarity.

![image](https://github.com/mbits-mirafra/axi4_avip/assets/106074838/2fbb174c-55a7-43a6-bc40-0dea1a82b94c)

**Comment by mahadevaswamy05** [comment]
**2.Here is the problem**

**when you sourced both directory source files like Setup.csh and you went for execution it will show the command not found.**

![image](https://github.com/mbits-mirafra/axi4_avip/assets/106074838/1733d595-a0ff-404f-ac1d-7afb858066d2)

The reason behind this is that Environment Variables are dynamic variables we are using for storing temporary paths in their respective directory. and the same env variable stores the different path so it gets overburdened and will show the command not found.

![image](https://github.com/mbits-mirafra/axi4_avip/assets/106074838/b88d129c-666b-430c-af33-5ca9146a40a4)

See this picture here the first green color frame will show the path for the SVUnit directory. and second, the mark thing of black color is another directory of the SVUnit1 path done there. so that's why it will show the command not found.

**Comment by mahadevaswamy05** [comment]
**3.Solution**

Just close that terminal and re-open it then source which directory source file you want, and go for execution it will not the any error like command not found.
